#!/bin/bash

echo "Starting server..."

cd RayneSQL || exit 1

cmd=(./mvnw clean compile exec:java@server)

if [[ "$1" == "-p" && "$2" =~ ^[0-9]+$ ]]; then
  port=$2
  
  if (( port >= 1024 && port <= 49151 )); then
    cmd=(./mvnw clean compile exec:java@server -Dexec.args="$port")
  else
    echo "ERROR: Port number must be between 1024 and 49151."
    exit 1
  fi
fi

"${cmd[@]}" | while IFS= read -r line; do
  if [[ "$line" == *"Server listening"* ]]; then
    echo "$line"

    while IFS= read -r next_line; do
      echo "$next_line"
    done
    break
  fi
done
